sudo: required
services:
    - docker

before_install:
    - docker build -t esachse/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true esachse/react-test npm test

after_success:
    - docker build -t esachse/multi-client ./client
    - docker build -t esachse/multi-nginx ./nginx
    - docker build -t esachse/multi-server ./server
    - docker build -t esachse/multi-worker ./worker
    # Login to Docker CLI
    - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    # Push images to docker hub
    - docker push esachse/multi-client
    - docker push esachse/multi-nginx
    - docker push esachse/multi-server
    - docker push esachse/multi-worker
    
